apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-multi
    image: nginx
    ports:
    - containerPort: 80  
  - name: alpine-multi
    image: alpine
    command: ["watch", "wget", "-qO-", "localhost"]
