apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
    tier: backend
spec:
    type: NodePort
    ports:
    - nodePort: 32306
      port: 3306
      targetPort: 3306
      protocol: TCP
    selector:
      app: mysql
      tier: backend
