apiVersion: networking.k8s.io/v1
kind: networkPolicy
metadata:
  name: networkpolicy-mysql
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tomcat # this need to be created 
      ports:
        - protocol: TCP
          port: 3306
