apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec: # Deployment Spec
  template:
    metadata: # Pod metadata
      labels:
        app: nginx-deployment
    spec: # Pod spec
      containers:
      - image: nginx
        name: nginx
  replicas: 4
  selector:
    matchLabels: # matches the labels on the pods
      app: nginx-deployment
