apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  nodeName: slave-node
