apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/www/html/"
    type: Directory
