apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-pv
  name: persistent-vol-service
spec:
  ports:
  - name: "nginx80"
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-pv
  type: NodePort
